name: execute rundoc on tutorials
run-name: execute rundoc on tutorials
on:
  schedule:
    # This schedule triggers the workflow at 00:00 every Monday
    - cron: "0 8 * * 1"
  workflow_dispatch:

# Disable all GITHUB_TOKEN permissions, since the GitHub App token is used instead.
permissions: {}

jobs:
  run-rundoc:
    runs-on: pub-hk-ubuntu-24.04-ip
    env:
      BUNDLE_GEMFILE: .rundoc-workspace/Gemfile
    steps:
      - name: Get token for GH application (Linguist)
        uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ vars.LINGUIST_GH_APP_ID }}
          private-key: ${{ secrets.LINGUIST_GH_PRIVATE_KEY }}

      - uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.generate-token.outputs.token }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true # do run 'bundle install' and cache
      - uses: buildpacks/github-actions/setup-pack@88d61b2f0183a156d3e0526e95cc19ab55daae5c # v5.9.7

      - name: Run rundoc for all languages
        run: |
          langs=("ruby" "dotnet" "nodejs" "python" "php" "go" "java_maven" "java_gradle" "scala")
          for lang in "${langs[@]}"; do
            bundle exec rundoc docs/src/$lang/RUNDOC.md \
              --on-success-dir docs/$lang \
              --on-failure-dir docs/fail/$lang \
              --force
          done
        continue-on-error: true
      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: rundoc-update
          delete-branch: true
          base: main
          commit-message: Update tutorials
          title: Update tutorials
          body: "generated by the [run-rundoc linux github action](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          committer: ${{ vars.LINGUIST_GH_APP_USERNAME }} <${{ vars.LINGUIST_GH_APP_EMAIL }}>
          author: ${{ vars.LINGUIST_GH_APP_USERNAME }} <${{ vars.LINGUIST_GH_APP_EMAIL }}>

      - name: Enable PR auto-merge
        if: steps.pr.outputs.pull-request-operation == 'created'
        run: gh pr merge --auto --squash "${{ steps.pr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
